# Generated by Django 3.2.18 on 2023-04-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cosecha', models.PositiveSmallIntegerField()),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('codigo', models.BigIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(default='catalogo/default.png', upload_to='catalogo/')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinventory.bodega')),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinventory.estante')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinventory.origen')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinventory.variedad')),
            ],
        ),
    ]
